repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-print, flake8-quotes, flake8-use-fstring]
        args: [--config=.flake8]