name: Code

on:
  push:
    branches:
      - main

jobs:
  validate:
    name: "Validate"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Run flake8
        run: |
          flake8 --config=.flake8 --statistics app main.py config.py
